
version: 2

sources:
  - name: sap_adw
    description: Source from Adventure Works sales database.
    schema: sap_adw
    tables:
      
      - name: product
        description: table of information about products.        
        columns:
          - name: productid
            description: It is a primary key from product table.

      - name: productsubcategory
        description: table of information about product subcategory.        
        columns:
          - name: productsubcategoryid
            description: It is a primary key from product subcategory table.

      - name: productmodel
        description: table of information about product model.        
        columns:
          - name: productmodelid
            description: It is a primary key from product model table.

      - name: productcategory
        description: table of information about product category.        
        columns:
          - name: productcategoryid
            description: It is a primary key from product category table.

      - name: address
        description: table of information about addresses.        
        columns:
          - name: addressid
            description: It is a primary key from addresses table.

      - name: stateprovince
        description: table of information about state province.        
        columns:
          - name: stateprovinceid
            description: It is a primary key from state province table.

      - name: countryregion
        description: table of information about country.        
        columns:
          - name: countryregioncode
            description: It is a primary key from country table.

      - name: person
        description: table of information about people in general.        
        columns:
          - name: businessentityid
            description: It is a foreign key from BusinessEntityID as a unique key from person table.

      - name: customer
        description: table of information about customer.        
        columns:
          - name: customerid
            description: It is a foreign key from BusinessEntityID as a unique key from customer table.

      - name: store
        description: table of information about stores and sales person assidned to the customer.        
        columns:
          - name: businessentityid
            description: It is a foreign key from BusinessEntityID as a unique key from store table.

      - name: productvendor
        description: table of information about purchased history product cost.

      - name: vendor
        description: table of information about verndores.        
        columns:
          - name: businessentityid
            description: It is a foreign key from BusinessEntityID as a unique key from vendor table.

      - name: purchaseorderdetail
        description: table of information about purchase details.        
        columns:
          - name: purchaseorderdetailid
            description: It is a primary key from purchase order details table.

      - name: purchaseorderheader
        description: table of information about purchases.        
        columns:
          - name: purchaseorderid
            description: It is a primary key from purchases table.

      - name: employee
        description: table of information about employees.        
        columns:
          - name: businessentityid
            description: It is a foreign key from BusinessEntityID as a unique key from employees table.

      - name: salesperson
        description: table of information about sales person.        
        columns:
          - name: businessentityid
            description: It is a foreign key from BusinessEntityID as a unique key from sales person table.

      - name: creditcard
        description: table of information about credit card.        
        columns:
          - name: creditcardid
            description: It is a primary key from credit card table.   

      - name: salesreason
        description: table of information about possible sales reasons.
        columns:
          - name: salesreasonid
            description: It is a primary key from sales reason table.

      - name: salesorderheadersalesreason
        description: table of information about the reason to that sale.
        columns:
          - name: salesorderid
            description: It is a foreign key from SalesOrderHeader to make a link with sales reason.

      - name: salesorderdetail
        description: table of information about the sales order details.
        columns:
          - name: salesorderdetailid
            description: It is a primary key from sales order details table.

      - name: salesorderheader
        description: table of information about the sales order.
        columns:
          - name: salesorderid
            description: It is a primary key from sales order table.

      - name: salesterritory
        description: table of information about the sales territory.        
        columns:
          - name: territoryid
            description: It is a primary key from sales territory table.                
          - name: continent
            description: This column has been renamed from group to continent. It shows the sales region by continents.

      - name: specialoffer
        description: table of information about the offers.
        columns:
          - name: specialofferid
            description: It is a primary key from special offers table.
            